### PR TITLE
Feature/update-shoot

### PR DESCRIPTION
**Pull request by oconn**
@JanxSpirit @mprichard @emilyseibert @thoughtmanifest @cch1 

I wanted to see if I could get some more eyes on this and also get opinions on the added gameplay idea (Detailed below).

Thanks for any help!

closes issue #45 

### Changes

- Add destroyed metadata when a shot destroys a space
- Add destroy space functionality to shoot
- Add player damage to shoot
- Add energy consumption logic to shooter
- Add energy reward logic to shooter
- Refactor initializers & finializers
- Add tests for shoot

### Added Gameplay Idea (Shoot Reward)

I added the concept of rewarding a player for shooting a space that is `destructible`. This is subject to change, but I kinda like the implication. Here's how it works.

- Player A gives 10 energy to it's shot.
- Player A's energy is decremented by 10.
- Shot can travel 10 spaces.

- *Space 1* open
    - The shots travel distance is reduced to 9
- *Space 2* block with 1 energy.
    - The block is destroyed
    - The shot's energy is reduced to 9
    - The shots travel distance is reduced to 8
    - Player A receives 1 energy back (Players will get back any energy that goes into damaging / destroying blocks)
- *Space 3* AI with 2 energy
    - The AI is destroyed
    - The shot's energy is reduced to 7
    - The shots travel distance is reduced to 7
    - Player A receives 4 energy (Players will get back 2x energy that goes into damaging / destroying an ai)
- *Space 4* Player B with 100 energy
    - Player B's energy is reduced to 93
    - The shot's energy is reduced to 0
    - The shots travel distance is reduced to 0
    - Player A receives 14 energy (Players will get back 2x energy that goes into damaging / destroying another player)

### CODE REVIEW

**Comment by cch1** [comment]
How far does the shot move per tick?

**Comment by cch1** [comment]
Typo?  Shot's travel distance is reduced to 8 twice.

**Comment by oconn** [comment]
Fixed the typo, it was supposed to be `7`. 

A shot is instant and will travel only as far as specified in the shot config. 

```clj
(def shot-settings {:can-occupy #{:open
                                  :ai
                                  :block
                                  :food
                                  :poison
                                  :fog
                                  :shoot}
                    :destructible #{:ai
                                    :block}
                    :distance 10})
```

**Comment by oconn** [comment]
I added a demo video to the #battlebots channel in the Cville slack as well

**Pull request merged**
