### PR TITLE
Feature/updated ai logic & bot helpers

### PR DESCRIPTION
**Pull request by oconn**
@thoughtmanifest I know you were talking about adding functions that will make writing bots a bit easier. I added a `bot-helpers` namespace with a few that I'm planning on using for the AI bots. If you get a few mins I'd like to get you opinion on them.

### CODE REVIEW

**Comment by thoughtmanifest** [comment]
I'll try to take a look at this tomorrow night.  I've got plans tonight.  One thing I immediately notice is the naming of the file.  Consider using directories and namespaces to help with organizing code.  For instance, consider a bot directory in the game directory.  Then in the bot directory there would be a helpers.clj so the namespace would be ...game.bot.helpers.  This same could be applied to decisions.  bot-decisions.clj could be renamed to decisions.clj  Does that make sense?

**Comment by oconn** [comment]
Yeah it does. I'll see if I get those changes in. Thanks!

**Comment by thoughtmanifest** [comment]
Another note based on looking a little closer, is the use of atoms, especially with reduce.  There should be a compelling reason to maintain state that I don't think is present in the bot helpers code.  Generally, you'd reach for an atom when dealing with concurrency or parallelism, not when traversing a collection as is done in those fns.  I'll try to present a better way to do what you're doing if I get a chance to work on this tonight, but I wanted to note it here as food for thought.

**Comment by oconn** [comment]
Yeah that didn't feel quite right. I could update the outer reduce to include counter and then just return the coords when it resolves. ?

**Comment by oconn** [comment]
So I refactored it to use `loop`. `get-items-coords` is now far more performant since will bail it finds a match. Let me know what you think.

**Comment by thoughtmanifest** [comment]
I like the change to loop.  I was also toying with a reduce version and a non-looping version of the sort-arena function.  Take a look:
```clojure
(defn- arena-by
  ([arena]
   (arena-by arena :type "none"))

  ([arena akey default]
   (apply concat
          (map-indexed
           #(map-indexed
             (fn [idx itm]
               (let [coords [idx %1]]
                 [(keyword (or (get itm akey) default)) (assoc itm :coords coords)]))
             %2)
           arena))))

(defn sort-arena2
  [arena]
  (reduce (fn [m [k v]]
            (update-in m [k] (fnil conj []) v))
          {}
          (arena-by arena)))

(defn- arena-by2
  ([arena]
   (arena-by2 arena :type "none"))

  ([arena akey default]
   (apply concat
          (map-indexed
           #(map-indexed
             (fn [idx itm]
               (let [coords [idx %1]]
                 {(keyword (or (get itm akey) default)) [(assoc itm :coords coords)]}))
             %2)
           arena))))

(defn sort-arena3
  [arena]
  (apply merge-with into (arena-by2 arena)))
```

What do you think?  It returns everything but the match key, but that could be easily added. I'm  wondering though, what the motivation is for the final data structure. How do you expect it to be used?

**Comment by oconn** [comment]
Oh I really like just adding the coords prop to the item instead of along side it. As for the decision on the data structure, I believe the return of `sort-arena` gives players a really easy way to evaluate their current environment (and probably even more so with `within-n-spaces` which operates on a sorted arena).  The plan for `bot.helpers` is to make it publicly accessible to anyone writing bots, (it is also in use for some of the ai logic). 

I'm liking the second sort method  that uses `arena-by2` a lot.  Which one are you leaning towards? I'm going to see if I can get that plugged in and update the `coords` in the other functions. Any thoughts, ideas, or additional helper functions would be much appreciated.

**Comment by thoughtmanifest** [comment]
Okay, I think that's pretty much what we were doing in the other bot code, looking around us, grabbing the interesting things and picking one of them at random to move towards. I do like the arena-by2 more as well.  So deliciously dense =)

One other note, I think we should change the type values to keywords.  That will simplify not just this code, but I think it's more clojurey to represent those values which don't have to be strings as keywords. Also, could be handy since you can use keywords as functions to maps in clojure. And if necessary, at the edges of the api you can call `(name type)` and get the string version.

**Comment by oconn** [comment]
Yeah I had that thought as well (changing types to keywords). I think I want that in a separate PR however so this one doesn't bloat too much. I added https://github.com/willowtreeapps/battlebots/issues/73 to track it.

**Comment by oconn** [comment]
Plug and play! Love it when you can confidently swap out code with tests to back you up. I went with the second arena sort method, let me know if you see anything else.

**Pull request merged**
